/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora.form;

import calculadora.operacoes.Calculo;
import calculadora.operacoes.Divisao;
import calculadora.operacoes.Multiplicacao;
import calculadora.operacoes.Porcentagem;
import calculadora.operacoes.Potenciacao;
import calculadora.operacoes.Adicao;
import calculadora.operacoes.Subtracao;
import java.math.BigDecimal;

/**
 *
 * @author Luciana
 */
public class CalcForm extends javax.swing.JFrame {

    /**
     * Creates new form CalcForm
     */
    private BigDecimal valorInicial = null;
    private Calculo calculo;

    public CalcForm() {
        initComponents();
        setLocationRelativeTo(null);
        jButCalcula.setEnabled(true);
    }

    private void setValorInicial() {
        valorInicial = new BigDecimal(jTexto.getText());
        jTexto.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButCalcula = new javax.swing.JButton();
        jBut10 = new javax.swing.JButton();
        jBut11 = new javax.swing.JButton();
        jBut12 = new javax.swing.JButton();
        jBut13 = new javax.swing.JButton();
        jBut14 = new javax.swing.JButton();
        jBut15 = new javax.swing.JButton();
        jBut16 = new javax.swing.JButton();
        jBut17 = new javax.swing.JButton();
        jBut8 = new javax.swing.JButton();
        jBut7 = new javax.swing.JButton();
        jBut9 = new javax.swing.JButton();
        jBut5 = new javax.swing.JButton();
        jBut4 = new javax.swing.JButton();
        jBut6 = new javax.swing.JButton();
        jBut1 = new javax.swing.JButton();
        jBut2 = new javax.swing.JButton();
        jTexto = new javax.swing.JTextField();
        jBut3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButCalcula.setBackground(new java.awt.Color(102, 204, 255));
        jButCalcula.setText("=");
        jButCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalculaActionPerformed(evt);
            }
        });

        jBut10.setText("0");
        jBut10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut10ActionPerformed(evt);
            }
        });

        jBut11.setText(".");
        jBut11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut11ActionPerformed(evt);
            }
        });

        jBut12.setText("-");
        jBut12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut12ActionPerformed(evt);
            }
        });

        jBut13.setText("+");
        jBut13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut13ActionPerformed(evt);
            }
        });

        jBut14.setText("x");
        jBut14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut14ActionPerformed(evt);
            }
        });

        jBut15.setText("÷");
        jBut15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut15ActionPerformed(evt);
            }
        });

        jBut16.setText("%");
        jBut16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut16ActionPerformed(evt);
            }
        });

        jBut17.setText("x^y");
        jBut17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut17ActionPerformed(evt);
            }
        });

        jBut8.setText("8");
        jBut8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut8ActionPerformed(evt);
            }
        });

        jBut7.setText("7");
        jBut7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut7ActionPerformed(evt);
            }
        });

        jBut9.setText("9");
        jBut9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut9ActionPerformed(evt);
            }
        });

        jBut5.setText("5");
        jBut5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut5ActionPerformed(evt);
            }
        });

        jBut4.setText("4");
        jBut4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut4ActionPerformed(evt);
            }
        });

        jBut6.setText("6");
        jBut6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut6ActionPerformed(evt);
            }
        });

        jBut1.setText("1");
        jBut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut1ActionPerformed(evt);
            }
        });

        jBut2.setText("2");
        jBut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut2ActionPerformed(evt);
            }
        });

        jTexto.setEditable(false);

        jBut3.setText("3");
        jBut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBut4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBut5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBut6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBut14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBut10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBut11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBut1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBut2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBut3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBut12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButCalcula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBut13))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBut17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBut16))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jBut7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBut8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBut9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBut15)))
                    .addComponent(jTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut16)
                    .addComponent(jBut17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut8)
                    .addComponent(jBut9)
                    .addComponent(jBut7)
                    .addComponent(jBut15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut5)
                    .addComponent(jBut6)
                    .addComponent(jBut4)
                    .addComponent(jBut14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut2)
                    .addComponent(jBut3)
                    .addComponent(jBut1)
                    .addComponent(jBut12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut11)
                    .addComponent(jBut10)
                    .addComponent(jButCalcula)
                    .addComponent(jBut13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalculaActionPerformed
        jTexto.setText("" + calculo.calcular(valorInicial, new BigDecimal(jTexto.getText())));
    }//GEN-LAST:event_jButCalculaActionPerformed

    private void jBut10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut10ActionPerformed
        jTexto.setText("0");
    }//GEN-LAST:event_jBut10ActionPerformed

    private void jBut11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut11ActionPerformed
        jTexto.setText(jTexto.getText().concat("."));
    }//GEN-LAST:event_jBut11ActionPerformed

    private void jBut12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut12ActionPerformed
        calculo = new Subtracao();
        setValorInicial();
    }//GEN-LAST:event_jBut12ActionPerformed

    private void jBut13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut13ActionPerformed
        calculo = new Adicao();
        setValorInicial();
    }//GEN-LAST:event_jBut13ActionPerformed

    private void jBut14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut14ActionPerformed
        calculo = new Multiplicacao();
        setValorInicial();
    }//GEN-LAST:event_jBut14ActionPerformed

    private void jBut15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut15ActionPerformed
        calculo = new Divisao();
        setValorInicial();
    }//GEN-LAST:event_jBut15ActionPerformed

    private void jBut16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut16ActionPerformed
        calculo = new Porcentagem();
        setValorInicial();
    }//GEN-LAST:event_jBut16ActionPerformed

    private void jBut17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut17ActionPerformed
        calculo = new Potenciacao();
        setValorInicial();
    }//GEN-LAST:event_jBut17ActionPerformed

    private void jBut8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut8ActionPerformed
        jTexto.setText(jTexto.getText() + "8");
    }//GEN-LAST:event_jBut8ActionPerformed

    private void jBut7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut7ActionPerformed
        jTexto.setText(jTexto.getText() + "7");
    }//GEN-LAST:event_jBut7ActionPerformed

    private void jBut9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut9ActionPerformed
        jTexto.setText(jTexto.getText() + "9");
    }//GEN-LAST:event_jBut9ActionPerformed

    private void jBut5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut5ActionPerformed
        jTexto.setText(jTexto.getText() + "5");
    }//GEN-LAST:event_jBut5ActionPerformed

    private void jBut4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut4ActionPerformed
        jTexto.setText(jTexto.getText() + "4");
    }//GEN-LAST:event_jBut4ActionPerformed

    private void jBut6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut6ActionPerformed
        jTexto.setText(jTexto.getText() + "6");
    }//GEN-LAST:event_jBut6ActionPerformed

    private void jBut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut1ActionPerformed
        jTexto.setText(jTexto.getText() + "1");
    }//GEN-LAST:event_jBut1ActionPerformed

    private void jBut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut2ActionPerformed
        jTexto.setText(jTexto.getText() + "2");
    }//GEN-LAST:event_jBut2ActionPerformed

    private void jBut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut3ActionPerformed
        jTexto.setText(jTexto.getText() + "3");
    }//GEN-LAST:event_jBut3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut1;
    private javax.swing.JButton jBut10;
    private javax.swing.JButton jBut11;
    private javax.swing.JButton jBut12;
    private javax.swing.JButton jBut13;
    private javax.swing.JButton jBut14;
    private javax.swing.JButton jBut15;
    private javax.swing.JButton jBut16;
    private javax.swing.JButton jBut17;
    private javax.swing.JButton jBut2;
    private javax.swing.JButton jBut3;
    private javax.swing.JButton jBut4;
    private javax.swing.JButton jBut5;
    private javax.swing.JButton jBut6;
    private javax.swing.JButton jBut7;
    private javax.swing.JButton jBut8;
    private javax.swing.JButton jBut9;
    private javax.swing.JButton jButCalcula;
    private javax.swing.JTextField jTexto;
    // End of variables declaration//GEN-END:variables
}
